### ISSUE TITLE
[Bug] Soul dont get removed on death

### ISSUE THREAD

**Issue by Davroom** [D-x-Z/SoulPoints#10]
**Describe the bug**
config doesnt reload unless server stopped
soul points dont get removed on death, 

**Logs**
no

**Server Version**
Paper version git-Paper-265 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 993f828)

**Plugins Version**
lattest

**Screenshots**

**Comment by VoChiDanh** [comment]
config doesnt reload unless server stopped -> so  `/souls reload ` doesn't work?

soul points dont get removed on death -> which jar you use to run? SoulPoints-Premium or SoulPoints-Legacy?

**Comment by VoChiDanh** [comment]
ok, i'll fix it soon. Join discord to get dev build faster 
discord.com/invite/2r4hm9bsp7

**Comment by VoChiDanh** [comment]
https://nightly.link/D-x-Z/SoulPoints/actions/runs/2014463402/[DevBuild]-SoulPoints.zip

Try it @Davroom 

SoulPoints-v1 --> Only work with MythicMobs 4.x.x & java 8+
SoulPoints-v2 --> Only work with MythicMobs 5.x.x & java 16+

**Comment by VoChiDanh** [comment]
https://nightly.link/D-x-Z/SoulPoints/actions/runs/2062458808/[DevBuild]-SoulPoints.zip
